name: "marketing_dbt_pipeline" # <--- Isay 'docs' hata kar simple kar dein
version: "1.0.0"
config-version: 2

profile: "marketing_dbt_pipeline" # <--- Ye ab profiles.yml se match kar raha hai

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing_dbt_pipeline: # <--- Yahan bhi naam change karein (Jo 'name' mein rakha hai)
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
