name: dbt_daily_build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: 

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        # v3 se v4 par upgrade kiya (Warning fix)
        uses: actions/checkout@v4

      - name: Setup Python
        # v4 se v5 par upgrade kiya (Warning fix)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-bigquery

      - name: Create GCP Key File
        run: |
          cat <<EOF > ./google_key.json
          ${{ secrets.GCP_SA_KEY }}
          EOF

      - name: Debug dbt Connection
        # Ye step check karega ke dbt ko profile mil rahi hai ya nahi
        run: |
          dbt debug --profiles-dir . --target prod

      - name: Run dbt Build
        run: |
          dbt build --profiles-dir . --target prod